version: '3.1'

services:
  postgres:
    image: postgres
    container_name : pg.award
    restart: always
    ports:
      - "5432:5432"
    networks: 
      - award
    environment:
      POSTGRES_USER : development-user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB : award
    volumes:
     - pgdata:/var/lib/postgresql/data

networks:
  award:

volumes:
  pgdata:
